Level/memdown

memdown.js
using a `undef` singleton, to distinguish between a not found value and a value that you _want_ to be `undefined`
=> fix undefined values

.travis.yml, .zuul.yml, README.md, package.json
Using Zuul and my own Saucelabs credentials.
=> Test in multiple Node versions and browsers

.gitignore, .travis.yml, README.md, package.json
Using Istanbul and Coveralls to test/report coverage.
=> add coverage tests and reporting

memdown.js
The iterators of `functional-red-black-tree` have an `update(value)` method. For keys that already exist, memdown can use this method to directly update the corresponding node, instead of removing it (for which RBTree itself uses an iterator) and then inserting a new node.
Performance of inserting new keys is the same, overwriting keys is 1.5 to twice as fast.
A [benchmark](https://gist.github.com/vweevers/ce8dddae626496b46183) ("remove and insert" is the current implementation, "update or insert" the new):
```sh
> matcha put-bench.js
put new key                  
32 op/s » remove and insert          
33 op/s » update or insert           
put existing key             
270 op/s » remove and insert          
486 op/s » update or insert           
```
```sh
> matcha batch-bench.js
put new …
```
=> Optimization: use RBTree's iterator.update in put and batch

package.json
Quick fix for #62. Should be published asap. @nolanlawson
=> Fix missing npm files (#62)

package.json
=> include memdown.d.ts in files property

memdown.d.ts, memdown.js
> dep: https://github.com/Level/abstract-leveldown/pull/129
* adds default export
=> typings: export as es2015 module + update

README.md
=> Readme: reduce testing section

README.md
Closes https://github.com/Level/memdown/issues/98
=> readme - update instantiation instructions

memdown.js, test.js
=> Remove skipping of falsy elements in batch array

CHANGELOG.md, README.md, memdown.js, package.json, test.js
Do not merge yet.
I can break this PR up but first I wanted to get feedback on the changes as a whole. You can follow the commits, or start with the readme and changelog.
=> New serialization

memdown.js
Closes #110. See also https://github.com/Level/abstract-leveldown/pull/168.
=> Buffer.isBuffer()

README.md, package.json
Closes https://github.com/Level/memdown/issues/95
Will squash this.
=> Tweak Readme

package.json
=> Update dependencies and remove rimraf

README.md, UPGRADING.md, package.json
=> Rename changelog to upgrade guide

CHANGELOG.md, UPGRADING.md
To address #125, starting with the upcoming v2 release.
=> Add changelog

.zuul.yml, CHANGELOG.md, memdown.js, package.json
See https://github.com/Level/memdown/issues/131#issuecomment-364458367.
=> Rename iterator#_end to fix conflict with abstract-leveldown

CHANGELOG.md, package.json
Closes https://github.com/Level/memdown/issues/130
=> configure greenkeeper to ignore @types/node

CHANGELOG.md, README.md
Closes https://github.com/Level/memdown/issues/127
=> readme: fix code example, obj.thing -> value.thing

.airtap.yml, .travis.yml, package.json
=> Use airtap instead of zuul

package.json
See https://github.com/Level/memdown/pull/150#issuecomment-386908081 and https://github.com/Level/community/issues/16 - the umpteenth cross-reference :)
=> Greenkeeper: ignore ts-node and typescript

memdown.js, package.json
See https://github.com/Level/community/issues/83
=> Add manifest

README.md
Ref https://github.com/Level/community/issues/113
=> Doc-deprecate
